server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://mysql-database:3306/kyc_test?createDatabaseIfNotExist=true
    username: root
    password: developer@@
  jpa:
    hibernate:
      ddl-auto: update
    properties: org.hibernate.dialect.MySQL5Dialect

